using System;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using GeneralUpdate.Core.JsonContext;

namespace GeneralUpdate.Core.Configuration;

/// <summary>
///     DTO for <c>generalupdate.manifest.json</c> — the application identity file generated by
///     <c>GeneralUpdate.Tools</c>. Contains only identity and structural metadata; secrets are
///     supplied in code via <see cref="GeneralUpdateBootstrap.SetSource"/>.
/// </summary>
public class ManifestInfo
{
    [JsonPropertyName("mainAppName")]
    public string MainAppName { get; set; }

    [JsonPropertyName("clientVersion")]
    public string ClientVersion { get; set; }

    [JsonPropertyName("appType")]
    public string AppType { get; set; }

    [JsonPropertyName("updateAppName")]
    public string UpdateAppName { get; set; } = "Update.exe";

    [JsonPropertyName("upgradeClientVersion")]
    public string UpgradeClientVersion { get; set; }

    [JsonPropertyName("productId")]
    public string ProductId { get; set; }

    [JsonPropertyName("updatePath")]
    public string UpdatePath { get; set; }

    private const string FileName = "generalupdate.manifest.json";

    /// <summary>
    ///     Load manifest from <see cref="AppDomain.CurrentDomain.BaseDirectory"/>.
    ///     Returns <c>null</c> when the file does not exist.
    /// </summary>
    public static ManifestInfo? Load()
    {
        var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, FileName);
        return Load(path);
    }

    /// <summary>
    ///     Load manifest from a specific path. Returns <c>null</c> when the file does not exist.
    /// </summary>
    public static ManifestInfo? Load(string path)
    {
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
            return null;

        try
        {
            var json = File.ReadAllText(path);
            return JsonSerializer.Deserialize(json, HttpParameterJsonContext.Default.ManifestInfo);
        }
        catch
        {
            // Malformed JSON, permission denied, etc. — treat as missing.
            return null;
        }
    }

    /// <summary>
    ///     Convert this manifest to a minimally populated <see cref="Configinfo"/>.
    ///     Caller must still supply secrets (<c>UpdateUrl</c>, <c>AppSecretKey</c>, <c>Token</c>).
    /// </summary>
    public Configinfo ToConfiginfo()
    {
        return new Configinfo
        {
            MainAppName = MainAppName,
            ClientVersion = ClientVersion,
            UpdateAppName = UpdateAppName ?? "Update.exe",
            UpgradeClientVersion = UpgradeClientVersion,
            ProductId = ProductId,
            UpdatePath = UpdatePath,
            AppType = Enum.TryParse<AppType>(AppType, out var at) ? at : null
        };
    }
}
