using System;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using GeneralUpdate.Core.JsonContext;

namespace GeneralUpdate.Core.Configuration;

/// <summary>
///     DTO for <c>generalupdate.manifest.json</c> — the application identity file generated by
///     <c>GeneralUpdate.Tools</c>. Contains only identity and structural metadata; secrets are
///     supplied in code via <see cref="GeneralUpdateBootstrap.SetSource"/>.
/// </summary>
public class ManifestInfo
{
    [JsonPropertyName("mainAppName")]
    public string MainAppName { get; set; }

    [JsonPropertyName("clientVersion")]
    public string ClientVersion { get; set; }

    [JsonPropertyName("appType")]
    public string AppType { get; set; }

    [JsonPropertyName("updateAppName")]
    public string UpdateAppName { get; set; } = "Update.exe";

    [JsonPropertyName("upgradeClientVersion")]
    public string UpgradeClientVersion { get; set; }

    [JsonPropertyName("productId")]
    public string ProductId { get; set; }

    [JsonPropertyName("updatePath")]
    public string UpdatePath { get; set; }

    private const string FileName = "generalupdate.manifest.json";

    /// <summary>
    ///     Load manifest from <see cref="AppDomain.CurrentDomain.BaseDirectory"/>.
    ///     Returns <c>null</c> when the file does not exist.
    /// </summary>
    public static ManifestInfo? Load()
    {
        var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, FileName);
        return Load(path);
    }

    /// <summary>
    ///     Load manifest from a specific path. Returns <c>null</c> when the file does not exist.
    /// </summary>
    public static ManifestInfo? Load(string path)
    {
        if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
            return null;

        try
        {
            var json = File.ReadAllText(path);
            return JsonSerializer.Deserialize(json, HttpParameterJsonContext.Default.ManifestInfo);
        }
        catch
        {
            // Malformed JSON, permission denied, etc. — treat as missing.
            return null;
        }
    }

    /// <summary>
    ///     Convert this manifest to a minimally populated <see cref="Configinfo"/>.
    ///     Caller must still supply secrets (<c>UpdateUrl</c>, <c>AppSecretKey</c>, <c>Token</c>).
    /// </summary>
    public Configinfo ToConfiginfo()
    {
        return new Configinfo
        {
            MainAppName = MainAppName,
            ClientVersion = ClientVersion,
            UpdateAppName = UpdateAppName ?? "Update.exe",
            UpgradeClientVersion = UpgradeClientVersion,
            ProductId = ProductId,
            UpdatePath = UpdatePath,
            AppType = Enum.TryParse<AppType>(AppType, out var at) ? at : null
        };
    }

    /// <summary>
    ///     Serialize this manifest back to the JSON file at the specified path, or
    ///     <see cref="AppDomain.CurrentDomain.BaseDirectory"/>/<c>generalupdate.manifest.json</c>
    ///     when <paramref name="path"/> is <c>null</c>.
    /// </summary>
    public void Save(string? path = null)
    {
        var filePath = path ?? Path.Combine(AppDomain.CurrentDomain.BaseDirectory, FileName);
        var json = JsonSerializer.Serialize(this, HttpParameterJsonContext.Default.ManifestInfo);
        File.WriteAllText(filePath, json);
    }

    /// <summary>
    ///     Load the manifest from <paramref name="baseDirectory"/>, update the specified version
    ///     fields, and save it back. Does nothing silently when the manifest file does not exist.
    /// </summary>
    /// <param name="baseDirectory">
    ///     The directory containing <c>generalupdate.manifest.json</c>.
    /// </param>
    /// <param name="clientVersion">
    ///     If non-null, overwrites <see cref="ClientVersion"/> with this value.
    /// </param>
    /// <param name="upgradeClientVersion">
    ///     If non-null, overwrites <see cref="UpgradeClientVersion"/> with this value.
    /// </param>
    public static void TryUpdateVersion(
        string baseDirectory,
        string? clientVersion = null,
        string? upgradeClientVersion = null)
    {
        var manifestPath = Path.Combine(baseDirectory, FileName);
        var manifest = Load(manifestPath);
        if (manifest == null) return;

        if (clientVersion != null)
            manifest.ClientVersion = clientVersion;
        if (upgradeClientVersion != null)
            manifest.UpgradeClientVersion = upgradeClientVersion;

        manifest.Save(manifestPath);
    }
}
