@GeneralUpdate.ProtectService_HostAddress = http://localhost:5276

GET {{GeneralUpdate.ProtectService_HostAddress}}/protect/
Accept: application/json

###

GET {{GeneralUpdate.ProtectService_HostAddress}}/protect/1
Accept: application/json

###