using System.Collections.Generic;

namespace GeneralUpdate.Core.FileSystem;

/// <summary>
/// Represents the result of a directory comparison operation, containing the full node lists for the left (base) and right (target) directories, as well as the list of differing nodes.
/// </summary>
/// <remarks>
/// <para>
/// ComparisonResult is generated by the <see cref="StorageManager.Compare"/> method.
/// It organizes the comparison results into three dimensions:
/// </para>
/// <list type="bullet">
///   <item><description><see cref="LeftNodes"/>: The list of all file nodes in the left directory.</description></item>
///   <item><description><see cref="RightNodes"/>: The list of all file nodes in the right directory.</description></item>
///   <item><description><see cref="DifferentNodes"/>: The collection of nodes identified by the <see cref="FileTree.Compare"/> algorithm
///   as having differing hash values or names (including added, modified, and deleted files).</description></item>
/// </list>
/// </remarks>
public class ComparisonResult
{
    private List<FileNode> _leftNodes;
    private List<FileNode> _rightNodes;
    private List<FileNode> _differentNodes;

    /// <summary>
    /// Initializes a new instance of the <see cref="ComparisonResult"/> class with all internal lists set to empty.
    /// </summary>
    public ComparisonResult()
    {
        _leftNodes = new List<FileNode>();
        _rightNodes = new List<FileNode>();
        _differentNodes = new List<FileNode>();
    }

    /// <summary>
    /// Gets a read-only list of all files in the left directory (base version).
    /// </summary>
    /// <value>A read-only collection of <see cref="FileNode"/> instances for the left directory.</value>
    public IReadOnlyList<FileNode> LeftNodes => _leftNodes.AsReadOnly();

    /// <summary>
    /// Gets a read-only list of all files in the right directory (target version).
    /// </summary>
    /// <value>A read-only collection of <see cref="FileNode"/> instances for the right directory.</value>
    public IReadOnlyList<FileNode> RightNodes => _rightNodes.AsReadOnly();

    /// <summary>
    /// Gets a read-only list of files that differ between the left and right directories.
    /// </summary>
    /// <value>A read-only collection of <see cref="FileNode"/> instances for the differing files.</value>
    /// <remarks>
    /// Differing nodes are obtained by recursively comparing the left and right <see cref="FileTree"/> instances,
    /// including files with different hash values or files that exist in only one directory.
    /// </remarks>
    public IReadOnlyList<FileNode> DifferentNodes => _differentNodes.AsReadOnly();

    /// <summary>
    /// Adds file nodes to the left nodes list.
    /// </summary>
    /// <param name="files">The collection of file nodes to add.</param>
    public void AddToLeft(IEnumerable<FileNode> files) => _leftNodes.AddRange(files);

    /// <summary>
    /// Adds file nodes to the right nodes list.
    /// </summary>
    /// <param name="files">The collection of file nodes to add.</param>
    public void AddToRight(IEnumerable<FileNode> files) => _rightNodes.AddRange(files);

    /// <summary>
    /// Adds file nodes to the differing nodes list.
    /// </summary>
    /// <param name="files">The collection of differing file nodes to add.</param>
    public void AddDifferent(IEnumerable<FileNode> files) => _differentNodes.AddRange(files);
}