using System.Threading;
using System.Threading.Tasks;
using GeneralUpdate.Differential.Abstractions;
using GeneralUpdate.Differential.Matchers;

namespace GeneralUpdate.Differential
{
    /// <summary>
    /// Entry point for differential update operations.
    /// </summary>
    /// <remarks>
    /// Parameterless overloads use <see cref="Differ.StreamingHdiffDiffer"/> with Brotli compression
    /// by default, producing smaller patches with faster application than the legacy BSDIFF algorithm.
    ///
    /// Supply an explicit <see cref="IBinaryDiffer"/> or custom <see cref="ICleanStrategy"/> /
    /// <see cref="IDirtyStrategy"/> for full control over the diff algorithm and execution flow.
    ///
    /// Legacy BSDIFF patches (generated by previous versions) remain fully readable via
    /// <see cref="Binary.BinaryHandler"/> when used as the differ.
    /// </remarks>
    public static class DifferentialCore
    {
        #region Clean (Patch Generation)

        /// <summary>
        /// Compares <paramref name="sourcePath"/> with <paramref name="targetPath"/> and
        /// writes patch artifacts to <paramref name="patchPath"/>.
        /// Defaults to StreamingHdiffDiffer with Brotli compression.
        /// </summary>
        public static Task Clean(string sourcePath, string targetPath, string patchPath, ICleanStrategy? strategy = null)
            => (strategy ?? new DefaultCleanStrategy()).ExecuteAsync(sourcePath, targetPath, patchPath);

        /// <summary>
        /// Compares <paramref name="sourcePath"/> with <paramref name="targetPath"/> and
        /// writes patch artifacts using the specified binary differ.
        /// </summary>
        /// <param name="binaryDiffer">
        /// The binary differ to use. When a non-null <paramref name="strategy"/> is provided,
        /// the strategy takes precedence and this parameter is ignored.
        /// </param>
        public static Task Clean(
            string sourcePath,
            string targetPath,
            string patchPath,
            IBinaryDiffer binaryDiffer,
            ICleanStrategy? strategy = null,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var cleanMatcher = new DefaultCleanMatcher();
            var usedStrategy = strategy ?? new DefaultCleanStrategy(cleanMatcher, binaryDiffer);
            return usedStrategy.ExecuteAsync(sourcePath, targetPath, patchPath);
        }

        #endregion Clean

        #region Dirty (Patch Application)

        /// <summary>
        /// Applies patches from <paramref name="patchPath"/> to the application files in
        /// <paramref name="appPath"/>.
        /// Defaults to StreamingHdiffDiffer with Brotli for fast decompression.
        /// Legacy BZip2 patches are auto-detected and handled transparently.
        /// </summary>
        public static Task Dirty(string appPath, string patchPath, IDirtyStrategy? strategy = null)
            => (strategy ?? new DefaultDirtyStrategy()).ExecuteAsync(appPath, patchPath);

        /// <summary>
        /// Applies patches using the specified binary differ.
        /// </summary>
        /// <param name="binaryDiffer">
        /// The binary differ to use. When a non-null <paramref name="strategy"/> is provided,
        /// the strategy takes precedence and this parameter is ignored.
        /// </param>
        public static Task Dirty(
            string appPath,
            string patchPath,
            IBinaryDiffer binaryDiffer,
            IDirtyStrategy? strategy = null,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var dirtyMatcher = new DefaultDirtyMatcher();
            var usedStrategy = strategy ?? new DefaultDirtyStrategy(dirtyMatcher, binaryDiffer);
            return usedStrategy.ExecuteAsync(appPath, patchPath);
        }

        #endregion Dirty
    }
}
