using System;
using System.Collections.Generic;
using System.Linq;

namespace GeneralUpdate.Core.FileSystem;

/// <summary>
/// Represents the comparison result of two file tree snapshots, containing lists of added, modified, and deleted files.
/// </summary>
/// <param name="Added">The list of file entries added in the new snapshot.</param>
/// <param name="Modified">The list of file entries that changed between the old and new snapshots (different size or last write time).</param>
/// <param name="Deleted">The list of relative paths for files that existed in the old snapshot but were removed in the new snapshot.</param>
/// <remarks>
/// <para>
/// FileTreeDiff is generated by the <see cref="FileTreeComparer.Compare"/> method,
/// providing three clear change sets for differential updates:
/// </para>
/// <list type="bullet">
///   <item><description><b>Added</b>: New files that need to be packaged directly into the update package.</description></item>
///   <item><description><b>Modified</b>: Changed files that need to be updated via differential patch or full replacement.</description></item>
///   <item><description><b>Deleted</b>: Removed files that need to be cleaned up from the client during update.</description></item>
/// </list>
/// <para>
/// Use <see cref="FileTreeDiff.HasChanges"/> to quickly check for any changes,
/// and <see cref="FileTreeDiff.TotalChanges"/> to get the total number of changes.
/// </para>
/// </remarks>
public readonly record struct FileTreeDiff(
    IReadOnlyList<FileEntry> Added,
    IReadOnlyList<FileEntry> Modified,
    IReadOnlyList<string> Deleted
)
{
    /// <summary>
    /// Gets a value indicating whether there are any changes (added, modified, or deleted).
    /// </summary>
    public bool HasChanges => Added.Count > 0 || Modified.Count > 0 || Deleted.Count > 0;

    /// <summary>
    /// Gets the total number of changes (added + modified + deleted).
    /// </summary>
    public int TotalChanges => Added.Count + Modified.Count + Deleted.Count;

    /// <summary>
    /// Gets an empty <see cref="FileTreeDiff"/> instance representing no changes.
    /// </summary>
    public static FileTreeDiff Empty { get; } = new(
        Array.Empty<FileEntry>(), Array.Empty<FileEntry>(), Array.Empty<string>());
}

/// <summary>
/// Compares two <see cref="FileTreeSnapshot"/> instances and generates a <see cref="FileTreeDiff"/> difference result.
/// Identifies files that have been added, modified, or deleted between the two file snapshots.
/// </summary>
/// <remarks>
/// <para>
/// FileTreeComparer is a key component in the differential update workflow, providing two comparison methods:
/// </para>
/// <list type="bullet">
///   <item><description><see cref="Compare"/>: Performs a full comparison and returns all lists of added, modified, and deleted files.</description></item>
///   <item><description><see cref="HasChanges(FileTreeSnapshot, FileTreeSnapshot)"/>: A quick check that
///   returns <c>true</c> as soon as the first difference is found, suitable for scenarios where only an "update available" check is needed.</description></item>
/// </list>
/// <para>
/// The comparison algorithm is based on a dictionary mapping of file relative paths, using <c>OrdinalIgnoreCase</c> string comparison
/// to ensure cross-platform compatibility. Whether a file has been modified is determined by comparing
/// <see cref="FileEntry.Size"/> and <see cref="FileEntry.LastWriteTimeUtc"/>.
/// </para>
/// </remarks>
public static class FileTreeComparer
{
    /// <summary>
    /// Compares two file system snapshots and returns the complete difference result.
    /// </summary>
    /// <param name="old">The old (base) file system snapshot.</param>
    /// <param name="updated">The new (target) file system snapshot.</param>
    /// <returns>A <see cref="FileTreeDiff"/> structure containing the lists of added, modified, and deleted files.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="old"/> or <paramref name="updated"/> is <c>null</c>.</exception>
    /// <remarks>
    /// <para>
    /// Comparison steps:
    /// <list type="number">
    ///   <item><description>Converts both the old and new snapshots into dictionaries keyed by <c>RelativePath</c>.</description></item>
    ///   <item><description>Iterates the new snapshot: if a path does not exist in the old snapshot, it is marked as "Added";
    ///   if it exists but has a different size or time, it is marked as "Modified".</description></item>
    ///   <item><description>Iterates the old snapshot: if a path does not exist in the new snapshot, it is marked as "Deleted".</description></item>
    /// </list>
    /// </para>
    /// </remarks>
    public static FileTreeDiff Compare(FileTreeSnapshot old, FileTreeSnapshot updated)
    {
        if (old == null) throw new ArgumentNullException(nameof(old));
        if (updated == null) throw new ArgumentNullException(nameof(updated));

        var oldMap = old.Entries.ToDictionary(e => e.RelativePath, e => e, StringComparer.OrdinalIgnoreCase);
        var newMap = updated.Entries.ToDictionary(e => e.RelativePath, e => e, StringComparer.OrdinalIgnoreCase);

        var added = new List<FileEntry>();
        var modified = new List<FileEntry>();
        var deleted = new List<string>();

        // Files present in updated but not in old → Added
        // Files present in updated and old with different size or time → Modified
        foreach (var kv in newMap)
        {
            var path = kv.Key;
            var entry = kv.Value;
            if (!oldMap.TryGetValue(path, out var oldEntry))
            {
                added.Add(entry);
            }
            else if (oldEntry.Size != entry.Size || oldEntry.LastWriteTimeUtc != entry.LastWriteTimeUtc)
            {
                modified.Add(entry);
            }
        }

        // Files present in old but not in updated → Deleted
        foreach (var path in oldMap.Keys)
        {
            if (!newMap.ContainsKey(path))
                deleted.Add(path);
        }

        return new FileTreeDiff(added.AsReadOnly(), modified.AsReadOnly(), deleted.AsReadOnly());
    }

    /// <summary>
    /// Quickly checks whether there are any changes between two file system snapshots (short-circuit mode).
    /// </summary>
    /// <param name="old">The old (base) file system snapshot.</param>
    /// <param name="updated">The new (target) file system snapshot.</param>
    /// <returns><c>true</c> if there are any file changes; otherwise, <c>false</c>.</returns>
    /// <remarks>
    /// Unlike <see cref="Compare"/>, this method returns <c>true</c> as soon as the first difference is found
    /// without continuing to traverse the remaining files. This makes it more performant in scenarios where
    /// only a boolean "update available" check is needed.
    /// It first performs a quick pre-check by comparing the total entry count, then examines each entry individually.
    /// </remarks>
    public static bool HasChanges(FileTreeSnapshot old, FileTreeSnapshot updated)
    {
        if (old.Entries.Count != updated.Entries.Count) return true;

        var oldMap = old.Entries.ToDictionary(e => e.RelativePath, e => e, StringComparer.OrdinalIgnoreCase);
        var newDict = updated.Entries.ToDictionary(e => e.RelativePath, e => e, StringComparer.OrdinalIgnoreCase);

        foreach (var kv in newDict)
        {
            if (!oldMap.TryGetValue(kv.Key, out var oldEntry)) return true;
            if (oldEntry.Size != kv.Value.Size || oldEntry.LastWriteTimeUtc != kv.Value.LastWriteTimeUtc) return true;
        }
        return false;
    }
}
